"""create_initial_tables

Revision ID: 61d5d08cc081
Revises: 
Create Date: 2026-06-20 20:10:24.211606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61d5d08cc081'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for user uniqueness.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email used for sign-in and communication.'),
    sa.Column('github_username', sa.String(length=100), nullable=True, comment='Nullable GitHub username associated via OAuth connection.'),
    sa.Column('auth_provider', sa.String(length=50), nullable=False, comment='Identity provider used (e.g., github, google, credentials).'),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', name='subscription_tier_enum'), server_default='free', nullable=False, comment='Determines LLM usage limits and premium feature accesses.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Flag for soft-ban or account suspension.'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp tracking user activity for session invalidation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record last update timestamp.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for repository records.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of this repository record. Cascade deletes repository when user is removed.'),
    sa.Column('github_url', sa.String(length=2048), nullable=False, comment='Full public HTTP repository URL.'),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False, comment='Unique repository ID generated by GitHub’s API to identify renamed repos.'),
    sa.Column('owner', sa.String(length=100), nullable=False, comment='Organization or user name owning the repo.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name of the repository.'),
    sa.Column('default_branch', sa.String(length=100), server_default='main', nullable=False, comment='Active default branch (e.g., main or master) used for file pulling.'),
    sa.Column('primary_language', sa.String(length=50), nullable=True, comment='Primary language of the repo as detected by GitHub.'),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='JSON map of all languages used and their byte count (from GitHub API).'),
    sa.Column('star_count', sa.Integer(), server_default='0', nullable=False, comment='Popularity metric of the repo to weigh project complexity.'),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=True, comment='Repository staleness indicator used to check if re-indexing is needed.'),
    sa.Column('analysis_status', sa.Enum('pending', 'analyzing', 'awaiting_review', 'generating', 'complete', 'failed', name='analysis_status_enum'), server_default='pending', nullable=False, comment='Aggregated user-facing status representing the state of the active analysis.'),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the latest completed execution run.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record last update timestamp.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_analysis_status'), 'repositories', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for the job.'),
    sa.Column('repository_id', sa.UUID(), nullable=False, comment='Repository being processed. Cascade deletes job records on repo removal.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Target user initiating the job. Cascade deletes job records on user deletion.'),
    sa.Column('celery_task_id', sa.UUID(), nullable=True, comment='Celery identifier to control, query, or terminate the OS process.'),
    sa.Column('langgraph_thread_id', sa.UUID(), nullable=False, comment='State key mapping the job run to the LangGraph Postgres checkpointer.'),
    sa.Column('status', sa.Enum('queued', 'running', 'interrupted', 'complete', 'failed', 'timed_out', name='job_status_enum'), server_default='queued', nullable=False, comment='Job execution state. Helps UI render correct loading overlays.'),
    sa.Column('current_node', sa.String(length=100), nullable=True, comment='Last active node in the LangGraph execution flow.'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Total retries attempted across LLM wrapper transient failures.'),
    sa.Column('error_message', sa.String(), nullable=True, comment='Raw stack trace or structured error description on execution failure.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp marking when the Celery task started execution.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp marking when job concluded (failed or completed).'),
    sa.Column('llm_tokens_used', sa.Integer(), server_default='0', nullable=False, comment='Sum of prompt and completion tokens used throughout this job.'),
    sa.Column('llm_cost_usd', sa.Numeric(precision=10, scale=6), server_default='0.000000', nullable=False, comment='Calculated dollar cost of the run based on model token pricing metrics.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record last update timestamp.'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_langgraph_thread_id'), 'analysis_jobs', ['langgraph_thread_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_langgraph_thread_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_analysis_status'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
