"""Add generated_outputs and output_downloads

Revision ID: 6c9b09ccbdd2
Revises: 61d5d08cc081
Create Date: 2026-06-21 17:39:31.817433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c9b09ccbdd2'
down_revision: Union[str, Sequence[str], None] = '61d5d08cc081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_outputs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID.'),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False, comment='Job run that generated this text output. Cascade deletes on job removal.'),
    sa.Column('output_type', sa.Enum('resume_bullets', 'linkedin_desc', 'readme', 'portfolio_doc', name='output_type_enum'), nullable=False, comment='Format target (e.g. resume bullet list, markdown readme).'),
    sa.Column('content', sa.String(), nullable=False, comment='The actual string text output generated.'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Incremental counter tracking revision counts of the outputs.'),
    sa.Column('is_current_version', sa.Boolean(), server_default='true', nullable=False, comment='Boolean flag indicating which version is active/visible.'),
    sa.Column('llm_model_used', sa.String(length=100), nullable=False, comment='LLM model descriptor used for tracing and cost tracking.'),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False, comment='Tokens sent in input.'),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False, comment='Tokens generated in output.'),
    sa.Column('generation_duration_ms', sa.Integer(), server_default='0', nullable=False, comment='Time taken for the generation API call to complete.'),
    sa.Column('minio_object_key', sa.String(length=1024), nullable=False, comment='Cloudflare R2 storage path for file retrieval.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record last update timestamp.'),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_outputs_analysis_job_id'), 'generated_outputs', ['analysis_job_id'], unique=False)
    op.create_table('output_downloads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID.'),
    sa.Column('output_id', sa.UUID(), nullable=False, comment='Reference to the downloaded generated file record. Cascade deletes on output removal.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User requesting download. Cascade deletes download logs on user deletion.'),
    sa.Column('format', sa.Enum('txt', 'md', 'pdf', 'json', name='download_format_enum'), nullable=False, comment='Downloaded format (txt, md, pdf, or json).'),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Exact access timestamp.'),
    sa.Column('presigned_url_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp for the presigned storage download URL.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record creation timestamp.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Record last update timestamp.'),
    sa.ForeignKeyConstraint(['output_id'], ['generated_outputs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_downloads_output_id'), 'output_downloads', ['output_id'], unique=False)
    op.create_index(op.f('ix_output_downloads_user_id'), 'output_downloads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_output_downloads_user_id'), table_name='output_downloads')
    op.drop_index(op.f('ix_output_downloads_output_id'), table_name='output_downloads')
    op.drop_table('output_downloads')
    op.drop_index(op.f('ix_generated_outputs_analysis_job_id'), table_name='generated_outputs')
    op.drop_table('generated_outputs')
    # ### end Alembic commands ###
