"""create_code_facts_and_embeddings_tables

Revision ID: 7374756ed0ba
Revises: a98385580fc5
Create Date: 2026-06-30 11:29:06.763208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '7374756ed0ba'
down_revision: Union[str, Sequence[str], None] = 'a98385580fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False, comment="Inferred rule representing the user's editing preference."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for the code fact.'),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False, comment='Analysis job that generated this fact.'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Category of technical information.'),
    sa.Column('claim', sa.String(), nullable=False, comment='Specific technical statement.'),
    sa.Column('source_file', sa.String(length=2048), nullable=False, comment='Path of the source file serving as evidence.'),
    sa.Column('snippet', sa.String(), nullable=False, comment='Extracted source code snippet.'),
    sa.Column('ats_impact', sa.String(), nullable=False, comment='Tailored resume/ATS bullet value explanation.'),
    sa.Column('is_validated', sa.Boolean(), server_default='false', nullable=False, comment='True if validation checks succeeded.'),
    sa.Column('is_human_approved', sa.Boolean(), server_default='false', nullable=False, comment='True if the user approved the fact in HiTL.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code_fact_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False, comment='Gemini text-embedding-004 768-dimensional float array.'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Model descriptor used to compute the embeddings.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['code_fact_id'], ['code_facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_fact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Checkpoint tables ignored
    op.drop_table('fact_embeddings')
    op.drop_table('code_facts')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
