"""add_is_private_to_repositories

Revision ID: a98385580fc5
Revises: 4cca4432d7df
Create Date: 2026-06-29 14:47:19.279964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a98385580fc5'
down_revision: Union[str, Sequence[str], None] = '4cca4432d7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False, comment='True if GitHub marked this repo private. Private repos are never shared across users.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_private')
    # ### end Alembic commands ###
