"""add_nextauth_and_usage_metric_tables

Revision ID: b3aec3e13708
Revises: 6c9b09ccbdd2
Create Date: 2026-06-21 20:35:45.235756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3aec3e13708'
down_revision: Union[str, Sequence[str], None] = '6c9b09ccbdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.String(length=255), nullable=False, comment='Verification subject identifier (e.g. email address).'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Secure validation token string.'),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False, comment='Verification token expiration timestamp.'),
    sa.PrimaryKeyConstraint('identifier', 'token'),
    sa.UniqueConstraint('token')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for account connection.'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='Reference to the users table. Cascade deletes on user removal.'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='OAuth provider account type (e.g. oauth, email, credentials).'),
    sa.Column('provider', sa.String(length=255), nullable=False, comment='OAuth identity provider name (e.g. github, google).'),
    sa.Column('providerAccountId', sa.String(length=255), nullable=False, comment='Unique identifier issued by OAuth provider for the user.'),
    sa.Column('refresh_token', sa.String(), nullable=True, comment='OAuth token refresh credential string.'),
    sa.Column('access_token', sa.String(), nullable=True, comment='OAuth active session token string.'),
    sa.Column('expires_at', sa.Integer(), nullable=True, comment='Active access token expiration epoch timestamp.'),
    sa.Column('token_type', sa.String(length=255), nullable=True, comment='Type of token returned (e.g. Bearer).'),
    sa.Column('scope', sa.String(length=255), nullable=True, comment='OAuth scope permissions list granted by provider.'),
    sa.Column('id_token', sa.String(), nullable=True, comment='OIDC ID token string.'),
    sa.Column('session_state', sa.String(length=255), nullable=True, comment='OAuth session state string.'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'providerAccountId', name='uq_accounts_provider_provider_account_id')
    )
    op.create_index(op.f('ix_accounts_provider'), 'accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_accounts_providerAccountId'), 'accounts', ['providerAccountId'], unique=False)
    op.create_index(op.f('ix_accounts_userId'), 'accounts', ['userId'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for login session.'),
    sa.Column('sessionToken', sa.String(length=255), nullable=False, comment='Secure session authentication token string.'),
    sa.Column('userId', sa.UUID(), nullable=False, comment='Reference to the users table. Cascade deletes on user removal.'),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False, comment='Session expiration timestamp.'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_sessionToken'), 'sessions', ['sessionToken'], unique=True)
    op.create_index(op.f('ix_sessions_userId'), 'sessions', ['userId'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key UUID for usage metric record.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User associated with this usage record.'),
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='The API endpoint accessed (e.g., /analyze, /regenerate).'),
    sa.Column('calls_count', sa.Integer(), server_default='1', nullable=False, comment='Number of times endpoint was called.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp of the usage occurrence.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_metrics_user_id'), 'usage_metrics', ['user_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True, comment='NextAuth user display name.'))
    op.add_column('users', sa.Column('emailVerified', sa.DateTime(timezone=True), nullable=True, comment='NextAuth timestamp when email was verified.'))
    op.add_column('users', sa.Column('image', sa.String(length=2048), nullable=True, comment='NextAuth profile image URL.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('users', 'emailVerified')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_usage_metrics_user_id'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_sessions_userId'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_sessionToken'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_accounts_userId'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_providerAccountId'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_provider'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
