import enum
import uuid
from datetime import datetime
from typing import Dict, Any, List, Optional
from sqlalchemy import String, Integer, BigInteger, Boolean, DateTime, Numeric, ForeignKey, Enum, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

# Database Enums
class SubscriptionTier(str, enum.Enum):
    FREE = "free"
    PRO = "pro"

class AnalysisStatus(str, enum.Enum):
    PENDING = "pending"
    ANALYZING = "analyzing"
    AWAITING_REVIEW = "awaiting_review"
    GENERATING = "generating"
    COMPLETE = "complete"
    FAILED = "failed"

class JobStatus(str, enum.Enum):
    QUEUED = "queued"
    RUNNING = "running"
    INTERRUPTED = "interrupted"
    COMPLETE = "complete"
    FAILED = "failed"
    TIMED_OUT = "timed_out"

# Models
class User(Base):
    """
    Primary user account table containing credentials, subscription tiers, and login tracking.
    """
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Primary key UUID for user uniqueness."
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique email used for sign-in and communication."
    )
    github_username: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="Nullable GitHub username associated via OAuth connection."
    )
    auth_provider: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Identity provider used (e.g., github, google, credentials)."
    )
    subscription_tier: Mapped[SubscriptionTier] = mapped_column(
        Enum(SubscriptionTier, name="subscription_tier_enum", values_callable=lambda obj: [e.value for e in obj]),
        nullable=False,
        default=SubscriptionTier.FREE,
        server_default="free",
        comment="Determines LLM usage limits and premium feature accesses."
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        comment="Flag for soft-ban or account suspension."
    )
    last_login_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp tracking user activity for session invalidation."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        comment="Record creation timestamp."
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=datetime.utcnow,
        comment="Record last update timestamp."
    )

    # Relationships
    repositories: Mapped[List["Repository"]] = relationship(
        "Repository",
        back_populates="user",
        cascade="all, delete-orphan"
    )
    analysis_jobs: Mapped[List["AnalysisJob"]] = relationship(
        "AnalysisJob",
        back_populates="user",
        cascade="all, delete-orphan"
    )


class Repository(Base):
    """
    Analyzed repository metadata synced from the GitHub API.
    """
    __tablename__ = "repositories"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Primary key UUID for repository records."
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Owner of this repository record. Cascade deletes repository when user is removed."
    )
    github_url: Mapped[str] = mapped_column(
        String(2048),
        nullable=False,
        comment="Full public HTTP repository URL."
    )
    github_repo_id: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
        comment="Unique repository ID generated by GitHub’s API to identify renamed repos."
    )
    owner: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Organization or user name owning the repo."
    )
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Name of the repository."
    )
    default_branch: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="main",
        server_default="main",
        comment="Active default branch (e.g., main or master) used for file pulling."
    )
    primary_language: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        comment="Primary language of the repo as detected by GitHub."
    )
    languages: Mapped[Dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
        comment="JSON map of all languages used and their byte count (from GitHub API)."
    )
    star_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Popularity metric of the repo to weigh project complexity."
    )
    last_commit_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Repository staleness indicator used to check if re-indexing is needed."
    )
    analysis_status: Mapped[AnalysisStatus] = mapped_column(
        Enum(AnalysisStatus, name="analysis_status_enum", values_callable=lambda obj: [e.value for e in obj]),
        nullable=False,
        default=AnalysisStatus.PENDING,
        server_default="pending",
        index=True,
        comment="Aggregated user-facing status representing the state of the active analysis."
    )
    last_analyzed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp of the latest completed execution run."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        comment="Record creation timestamp."
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=datetime.utcnow,
        comment="Record last update timestamp."
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="repositories")
    analysis_jobs: Mapped[List["AnalysisJob"]] = relationship(
        "AnalysisJob",
        back_populates="repository",
        cascade="all, delete-orphan"
    )


class AnalysisJob(Base):
    """
    Execution records of LangGraph pipelines dispatched via Celery.
    """
    __tablename__ = "analysis_jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Primary key UUID for the job."
    )
    repository_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Repository being processed. Cascade deletes job records on repo removal."
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Target user initiating the job. Cascade deletes job records on user deletion."
    )
    celery_task_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        comment="Celery identifier to control, query, or terminate the OS process."
    )
    langgraph_thread_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="State key mapping the job run to the LangGraph Postgres checkpointer."
    )
    status: Mapped[JobStatus] = mapped_column(
        Enum(JobStatus, name="job_status_enum", values_callable=lambda obj: [e.value for e in obj]),
        nullable=False,
        default=JobStatus.QUEUED,
        server_default="queued",
        index=True,
        comment="Job execution state. Helps UI render correct loading overlays."
    )
    current_node: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="Last active node in the LangGraph execution flow."
    )
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Total retries attempted across LLM wrapper transient failures."
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,
        comment="Raw stack trace or structured error description on execution failure."
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp marking when the Celery task started execution."
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp marking when job concluded (failed or completed)."
    )
    llm_tokens_used: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Sum of prompt and completion tokens used throughout this job."
    )
    llm_cost_usd: Mapped[float] = mapped_column(
        Numeric(10, 6),
        nullable=False,
        default=0.0,
        server_default="0.000000",
        comment="Calculated dollar cost of the run based on model token pricing metrics."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        comment="Record creation timestamp."
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=datetime.utcnow,
        comment="Record last update timestamp."
    )

    # Relationships
    repository: Mapped["Repository"] = relationship("Repository", back_populates="analysis_jobs")
    user: Mapped["User"] = relationship("User", back_populates="analysis_jobs")
